name: ClayBrizendine
favicon: null
layout_spectrum: 0.6492945624049753
typography_spectrum: 0.6987064182758331
title: Clay Brizendine
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5252471461426467
  lightness: 0.8694703427609056
  saturation: 0.8083901135250926
  rhythmicContrast: 0.7724886105861515
purpose: []
